/* eslint-disable prettier/prettier */
// eslint-disable-next-line import/prefer-default-export
export function getDefaultCountryName(lng: string, text: string) {
  if (lng == 'ru') {
    switch (text) {
      case 'Беларусь':
        return 'Belarus'
      case 'Польша':
        return 'Poland'
      case 'Украина':
        return 'Ukraine'
      case 'Россия':
        return 'Russia'
    }
  }
  if (lng == 'en') {
    return text
  }
}

export const exchangePlatformFees = {
  BYBIT: {
    bep20: { min: 10, fee: 1.3 },
    trc20: { min: 2.6, fee: 1.3 }
  },
  BINANCE: {
    bep20: { min: 5, fee: 0.33 },
    trc20: { min: 4, fee: 1 }
  },
  SIGEN: {
    bep20: { min: 10, fee: 3 },
    trc20: { min: 10, fee: 3.5 },
  },
  OKEX: {
    bep20: { min: 3, fee: 2 },
    trc20: { min: 3, fee: 1 }
  },
  HUOBI: {
    bep20: { min: 3, fee: 2 },
    trc20: { min: 2, fee: 1 }
  },
  GARANTEX: {
    bep20: { min: 1, fee: 1 },
    trc20: { min: 0.5, fee: 2.5 }
  },
  BITPAPA: {
    bep20: null, // do not support
    trc20: { min: 2, fee: 1 }
  },
  GATE_IO: {
    bep20: { min: 1.5, fee: 0.5 },
    trc20: { min: 2, fee: 1 }
  },
  EMCD: {
    bep20: { min: 1, fee: 1 },
    trc20: { min: 1, fee: 1 }
  },
  POLONIEX: {
    bep20: null, // do not support
    trc20: { min: 3, fee: 2 }
  },
  MEXC: {
    bep20: { min: 1.1, fee: 0.5 },
    trc20: { min: 3, fee: 1 }
  },
  TG_WALLET: {
    bep20: null, // do not support
    trc20: { min: 1, fee: 2 }
  },
};


export const flagCountryMap = {
  '🇦🇫': { name: 'Afghanistan', code: 'AF' },
  '🇦🇱': { name: 'Albania', code: 'AL' },
  '🇩🇿': { name: 'Algeria', code: 'DZ' },
  '🇦🇸': { name: 'American Samoa', code: 'AS' },
  '🇦🇩': { name: 'Andorra', code: 'AD' },
  '🇦🇴': { name: 'Angola', code: 'AO' },
  '🇦🇮': { name: 'Anguilla', code: 'AI' },
  '🇦🇬': { name: 'Antigua and Barbuda', code: 'AG' },
  '🇦🇷': { name: 'Argentina', code: 'AR' },
  '🇦🇲': { name: 'Armenia', code: 'AM' },
  '🇦🇼': { name: 'Aruba', code: 'AW' },
  '🇦🇺': { name: 'Australia', code: 'AU' },
  '🇦🇹': { name: 'Austria', code: 'AT' },
  '🇦🇿': { name: 'Azerbaijan', code: 'AZ' },
  '🇧🇸': { name: 'Bahamas', code: 'BS' },
  '🇧🇭': { name: 'Bahrain', code: 'BH' },
  '🇧🇩': { name: 'Bangladesh', code: 'BD' },
  '🇧🇧': { name: 'Barbados', code: 'BB' },
  '🇧🇾': { name: 'Belarus', code: 'BY' },
  '🇧🇪': { name: 'Belgium', code: 'BE' },
  '🇧🇿': { name: 'Belize', code: 'BZ' },
  '🇧🇯': { name: 'Benin', code: 'BJ' },
  '🇧🇲': { name: 'Bermuda', code: 'BM' },
  '🇧🇹': { name: 'Bhutan', code: 'BT' },
  '🇧🇴': { name: 'Bolivia', code: 'BO' },
  '🇧🇦': { name: 'Bosnia and Herzegovina', code: 'BA' },
  '🇧🇼': { name: 'Botswana', code: 'BW' },
  '🇧🇷': { name: 'Brazil', code: 'BR' },
  '🇧🇳': { name: 'Brunei', code: 'BN' },
  '🇧🇬': { name: 'Bulgaria', code: 'BG' },
  '🇧🇫': { name: 'Burkina Faso', code: 'BF' },
  '🇧🇮': { name: 'Burundi', code: 'BI' },
  '🇰🇭': { name: 'Cambodia', code: 'KH' },
  '🇨🇲': { name: 'Cameroon', code: 'CM' },
  '🇨🇦': { name: 'Canada', code: 'CA' },
  '🇨🇻': { name: 'Cape Verde', code: 'CV' },
  '🇧🇶': { name: 'Caribbean Netherlands', code: 'BQ' },
  '🇰🇾': { name: 'Cayman Islands', code: 'KY' },
  '🇨🇫': { name: 'Central African Republic', code: 'CF' },
  '🇹🇩': { name: 'Chad', code: 'TD' },
  '🇨🇱': { name: 'Chile', code: 'CL' },
  '🇨🇳': { name: 'China', code: 'CN' },
  '🇨🇽': { name: 'Christmas Island', code: 'CX' },
  '🇨🇨': { name: 'Cocos (Keeling) Islands', code: 'CC' },
  '🇨🇴': { name: 'Colombia', code: 'CO' },
  '🇰🇲': { name: 'Comoros', code: 'KM' },
  '🇨🇬': { name: 'Congo - Brazzaville', code: 'CG' },
  '🇨🇩': { name: 'Congo - Kinshasa', code: 'CD' },
  '🇨🇰': { name: 'Cook Islands', code: 'CK' },
  '🇨🇷': { name: 'Costa Rica', code: 'CR' },
  '🇭🇷': { name: 'Croatia', code: 'HR' },
  '🇨🇺': { name: 'Cuba', code: 'CU' },
  '🇨🇼': { name: 'Curaçao', code: 'CW' },
  '🇨🇾': { name: 'Cyprus', code: 'CY' },
  '🇨🇿': { name: 'Czechia', code: 'CZ' },
  '🇩🇰': { name: 'Denmark', code: 'DK' },
  '🇩🇯': { name: 'Djibouti', code: 'DJ' },
  '🇩🇲': { name: 'Dominica', code: 'DM' },
  '🇩🇴': { name: 'Dominican Republic', code: 'DO' },
  '🇪🇨': { name: 'Ecuador', code: 'EC' },
  '🇪🇬': { name: 'Egypt', code: 'EG' },
  '🇸🇻': { name: 'El Salvador', code: 'SV' },
  '🇬🇶': { name: 'Equatorial Guinea', code: 'GQ' },
  '🇪🇷': { name: 'Eritrea', code: 'ER' },
  '🇪🇪': { name: 'Estonia', code: 'EE' },
  '🇪🇹': { name: 'Ethiopia', code: 'ET' },
  '🇫🇰': { name: 'Falkland Islands', code: 'FK' },
  '🇫🇴': { name: 'Faroe Islands', code: 'FO' },
  '🇫🇯': { name: 'Fiji', code: 'FJ' },
  '🇫🇮': { name: 'Finland', code: 'FI' },
  '🇫🇷': { name: 'France', code: 'FR' },
  '🇬🇫': { name: 'French Guiana', code: 'GF' },
  '🇵🇫': { name: 'French Polynesia', code: 'PF' },
  '🇹🇫': { name: 'French Southern Territories', code: 'TF' },
  '🇬🇦': { name: 'Gabon', code: 'GA' },
  '🇬🇲': { name: 'Gambia', code: 'GM' },
  '🇬🇪': { name: 'Georgia', code: 'GE' },
  '🇩🇪': { name: 'Germany', code: 'DE' },
  '🇬🇭': { name: 'Ghana', code: 'GH' },
  '🇬🇮': { name: 'Gibraltar', code: 'GI' },
  '🇬🇷': { name: 'Greece', code: 'GR' },
  '🇬🇱': { name: 'Greenland', code: 'GL' },
  '🇬🇩': { name: 'Grenada', code: 'GD' },
  '🇬🇵': { name: 'Guadeloupe', code: 'GP' },
  '🇬🇺': { name: 'Guam', code: 'GU' },
  '🇬🇹': { name: 'Guatemala', code: 'GT' },
  '🇬🇬': { name: 'Guernsey', code: 'GG' },
  '🇬🇳': { name: 'Guinea', code: 'GN' },
  '🇬🇼': { name: 'Guinea-Bissau', code: 'GW' },
  '🇬🇾': { name: 'Guyana', code: 'GY' },
  '🇭🇹': { name: 'Haiti', code: 'HT' },
  '🇭🇳': { name: 'Honduras', code: 'HN' },
  '🇭🇰': { name: 'Hong Kong SAR China', code: 'HK' },
  '🇭🇺': { name: 'Hungary', code: 'HU' },
  '🇮🇸': { name: 'Iceland', code: 'IS' },
  '🇮🇳': { name: 'India', code: 'IN' },
  '🇮🇩': { name: 'Indonesia', code: 'ID' },
  '🇮🇷': { name: 'Iran', code: 'IR' },
  '🇮🇶': { name: 'Iraq', code: 'IQ' },
  '🇮🇪': { name: 'Ireland', code: 'IE' },
  '🇮🇲': { name: 'Isle of Man', code: 'IM' },
  '🇮🇱': { name: 'Israel', code: 'IL' },
  '🇮🇹': { name: 'Italy', code: 'IT' },
  '🇯🇲': { name: 'Jamaica', code: 'JM' },
  '🇯🇵': { name: 'Japan', code: 'JP' },
  '🇯🇪': { name: 'Jersey', code: 'JE' },
  '🇯🇴': { name: 'Jordan', code: 'JO' },
  '🇰🇿': { name: 'Kazakhstan', code: 'KZ' },
  '🇰🇪': { name: 'Kenya', code: 'KE' },
  '🇰🇮': { name: 'Kiribati', code: 'KI' },
  '🇰🇼': { name: 'Kuwait', code: 'KW' },
  '🇰🇬': { name: 'Kyrgyzstan', code: 'KG' },
  '🇱🇦': { name: 'Laos', code: 'LA' },
  '🇱🇻': { name: 'Latvia', code: 'LV' },
  '🇱🇧': { name: 'Lebanon', code: 'LB' },
  '🇱🇸': { name: 'Lesotho', code: 'LS' },
  '🇱🇷': { name: 'Liberia', code: 'LR' },
  '🇱🇾': { name: 'Libya', code: 'LY' },
  '🇱🇮': { name: 'Liechtenstein', code: 'LI' },
  '🇱🇹': { name: 'Lithuania', code: 'LT' },
  '🇱🇺': { name: 'Luxembourg', code: 'LU' },
  '🇲🇴': { name: 'Macau SAR China', code: 'MO' },
  '🇲🇬': { name: 'Madagascar', code: 'MG' },
  '🇲🇼': { name: 'Malawi', code: 'MW' },
  '🇲🇾': { name: 'Malaysia', code: 'MY' },
  '🇲🇻': { name: 'Maldives', code: 'MV' },
  '🇲🇱': { name: 'Mali', code: 'ML' },
  '🇲🇹': { name: 'Malta', code: 'MT' },
  '🇲🇭': { name: 'Marshall Islands', code: 'MH' },
  '🇲🇶': { name: 'Martinique', code: 'MQ' },
  '🇲🇷': { name: 'Mauritania', code: 'MR' },
  '🇲🇺': { name: 'Mauritius', code: 'MU' },
  '🇾🇹': { name: 'Mayotte', code: 'YT' },
  '🇲🇽': { name: 'Mexico', code: 'MX' },
  '🇫🇲': { name: 'Micronesia', code: 'FM' },
  '🇲🇩': { name: 'Moldova', code: 'MD' },
  '🇲🇨': { name: 'Monaco', code: 'MC' },
  '🇲🇳': { name: 'Mongolia', code: 'MN' },
  '🇲🇪': { name: 'Montenegro', code: 'ME' },
  '🇲🇸': { name: 'Montserrat', code: 'MS' },
  '🇲🇦': { name: 'Morocco', code: 'MA' },
  '🇲🇿': { name: 'Mozambique', code: 'MZ' },
  '🇲🇲': { name: 'Myanmar (Burma)', code: 'MM' },
  '🇳🇦': { name: 'Namibia', code: 'NA' },
  '🇳🇷': { name: 'Nauru', code: 'NR' },
  '🇳🇵': { name: 'Nepal', code: 'NP' },
  '🇳🇱': { name: 'Netherlands', code: 'NL' },
  '🇳🇨': { name: 'New Caledonia', code: 'NC' },
  '🇳🇿': { name: 'New Zealand', code: 'NZ' },
  '🇳🇮': { name: 'Nicaragua', code: 'NI' },
  '🇳🇪': { name: 'Niger', code: 'NE' },
  '🇳🇬': { name: 'Nigeria', code: 'NG' },
  '🇳🇺': { name: 'Niue', code: 'NU' },
  '🇳🇫': { name: 'Norfolk Island', code: 'NF' },
  '🇰🇵': { name: 'North Korea', code: 'KP' },
  '🇲🇰': { name: 'North Macedonia', code: 'MK' },
  '🇲🇵': { name: 'Northern Mariana Islands', code: 'MP' },
  '🇳🇴': { name: 'Norway', code: 'NO' },
  '🇴🇲': { name: 'Oman', code: 'OM' },
  '🇵🇰': { name: 'Pakistan', code: 'PK' },
  '🇵🇼': { name: 'Palau', code: 'PW' },
  '🇵🇸': { name: 'Palestine', code: 'PS' },
  '🇵🇦': { name: 'Panama', code: 'PA' },
  '🇵🇬': { name: 'Papua New Guinea', code: 'PG' },
  '🇵🇾': { name: 'Paraguay', code: 'PY' },
  '🇵🇪': { name: 'Peru', code: 'PE' },
  '🇵🇭': { name: 'Philippines', code: 'PH' },
  '🇵🇳': { name: 'Pitcairn Islands', code: 'PN' },
  '🇵🇱': { name: 'Poland', code: 'PL' },
  '🇵🇹': { name: 'Portugal', code: 'PT' },
  '🇵🇷': { name: 'Puerto Rico', code: 'PR' },
  '🇶🇦': { name: 'Qatar', code: 'QA' },
  '🇷🇪': { name: 'Réunion', code: 'RE' },
  '🇷🇴': { name: 'Romania', code: 'RO' },
  '🇷🇺': { name: 'Russia', code: 'RU' },
  '🇷🇼': { name: 'Rwanda', code: 'RW' },
  '🇼🇸': { name: 'Samoa', code: 'WS' },
  '🇸🇲': { name: 'San Marino', code: 'SM' },
  '🇸🇹': { name: 'São Tomé & Príncipe', code: 'ST' },
  '🇸🇦': { name: 'Saudi Arabia', code: 'SA' },
  '🇸🇳': { name: 'Senegal', code: 'SN' },
  '🇷🇸': { name: 'Serbia', code: 'RS' },
  '🇸🇨': { name: 'Seychelles', code: 'SC' },
  '🇸🇱': { name: 'Sierra Leone', code: 'SL' },
  '🇸🇬': { name: 'Singapore', code: 'SG' },
  '🇸🇽': { name: 'Sint Maarten', code: 'SX' },
  '🇸🇰': { name: 'Slovakia', code: 'SK' },
  '🇸🇮': { name: 'Slovenia', code: 'SI' },
  '🇸🇧': { name: 'Solomon Islands', code: 'SB' },
  '🇸🇴': { name: 'Somalia', code: 'SO' },
  '🇿🇦': { name: 'South Africa', code: 'ZA' },
  '🇬🇸': { name: 'South Georgia & South Sandwich Islands', code: 'GS' },
  '🇰🇷': { name: 'South Korea', code: 'KR' },
  '🇸🇸': { name: 'South Sudan', code: 'SS' },
  '🇪🇸': { name: 'Spain', code: 'ES' },
  '🇱🇰': { name: 'Sri Lanka', code: 'LK' },
  '🇧🇱': { name: 'St. Barthélemy', code: 'BL' },
  '🇸🇭': { name: 'St. Helena', code: 'SH' },
  '🇰🇳': { name: 'St. Kitts & Nevis', code: 'KN' },
  '🇱🇨': { name: 'St. Lucia', code: 'LC' },
  '🇲🇫': { name: 'St. Martin', code: 'MF' },
  '🇵🇲': { name: 'St. Pierre & Miquelon', code: 'PM' },
  '🇻🇨': { name: 'St. Vincent & Grenadines', code: 'VC' },
  '🇸🇩': { name: 'Sudan', code: 'SD' },
  '🇸🇷': { name: 'Suriname', code: 'SR' },
  '🇸🇯': { name: 'Svalbard & Jan Mayen', code: 'SJ' },
  '🇸🇪': { name: 'Sweden', code: 'SE' },
  '🇨🇭': { name: 'Switzerland', code: 'CH' },
  '🇸🇾': { name: 'Syria', code: 'SY' },
  '🇹🇼': { name: 'Taiwan', code: 'TW' },
  '🇹🇯': { name: 'Tajikistan', code: 'TJ' },
  '🇹🇿': { name: 'Tanzania', code: 'TZ' },
  '🇹🇭': { name: 'Thailand', code: 'TH' },
  '🇹🇱': { name: 'Timor-Leste', code: 'TL' },
  '🇹🇬': { name: 'Togo', code: 'TG' },
  '🇹🇰': { name: 'Tokelau', code: 'TK' },
  '🇹🇴': { name: 'Tonga', code: 'TO' },
  '🇹🇹': { name: 'Trinidad & Tobago', code: 'TT' },
  '🇹🇳': { name: 'Tunisia', code: 'TN' },
  '🇹🇷': { name: 'Turkey', code: 'TR' },
  '🇹🇲': { name: 'Turkmenistan', code: 'TM' },
  '🇹🇨': { name: 'Turks & Caicos Islands', code: 'TC' },
  '🇹🇻': { name: 'Tuvalu', code: 'TV' },
  '🇺🇬': { name: 'Uganda', code: 'UG' },
  '🇺🇦': { name: 'Ukraine', code: 'UA' },
  '🇦🇪': { name: 'United Arab Emirates', code: 'AE' },
  '🇬🇧': { name: 'United Kingdom', code: 'GB' },
  '🇺🇸': { name: 'United States', code: 'US' },
  '🇻🇮': { name: 'U.S. Virgin Islands', code: 'VI' },
  '🇺🇾': { name: 'Uruguay', code: 'UY' },
  '🇺🇿': { name: 'Uzbekistan', code: 'UZ' },
  '🇻🇺': { name: 'Vanuatu', code: 'VU' },
  '🇻🇦': { name: 'Vatican City', code: 'VA' },
  '🇻🇪': { name: 'Venezuela', code: 'VE' },
  '🇻🇳': { name: 'Vietnam', code: 'VN' },
  '🇼🇫': { name: 'Wallis & Futuna', code: 'WF' },
  '🇪🇭': { name: 'Western Sahara', code: 'EH' },
  '🇾🇪': { name: 'Yemen', code: 'YE' },
  '🇿🇲': { name: 'Zambia', code: 'ZM' },
  '🇿🇼': { name: 'Zimbabwe', code: 'ZW' }
};


export const countryCurrencyMap = {
  'Afghanistan': 'AFN',
  'Albania': 'ALL',
  'Algeria': 'DZD',
  'American Samoa': 'USD',
  'Andorra': 'EUR',
  'Angola': 'AOA',
  'Anguilla': 'XCD',
  'Antigua and Barbuda': 'XCD',
  'Argentina': 'ARS',
  'Armenia': 'AMD',
  'Aruba': 'AWG',
  'Australia': 'AUD',
  'Austria': 'EUR',
  'Azerbaijan': 'AZN',
  'Bahamas': 'BSD',
  'Bahrain': 'BHD',
  'Bangladesh': 'BDT',
  'Barbados': 'BBD',
  'Belarus': 'BYN',
  'Belgium': 'EUR',
  'Belize': 'BZD',
  'Benin': 'XOF',
  'Bermuda': 'BMD',
  'Bhutan': 'BTN',
  'Bolivia': 'BOB',
  'Bosnia and Herzegovina': 'BAM',
  'Botswana': 'BWP',
  'Brazil': 'BRL',
  'Brunei': 'BND',
  'Bulgaria': 'BGN',
  'Burkina Faso': 'XOF',
  'Burundi': 'BIF',
  'Cambodia': 'KHR',
  'Cameroon': 'XAF',
  'Canada': 'CAD',
  'Cape Verde': 'CVE',
  'Caribbean Netherlands': 'USD',
  'Cayman Islands': 'KYD',
  'Central African Republic': 'XAF',
  'Chad': 'XAF',
  'Chile': 'CLP',
  'China': 'CNY',
  'Christmas Island': 'AUD',
  'Cocos (Keeling) Islands': 'AUD',
  'Colombia': 'COP',
  'Comoros': 'KMF',
  'Congo - Brazzaville': 'XAF',
  'Congo - Kinshasa': 'CDF',
  'Cook Islands': 'NZD',
  'Costa Rica': 'CRC',
  'Croatia': 'HRK',
  'Cuba': 'CUP',
  'Curaçao': 'ANG',
  'Cyprus': 'EUR',
  'Czechia': 'CZK',
  'Denmark': 'DKK',
  'Djibouti': 'DJF',
  'Dominica': 'XCD',
  'Dominican Republic': 'DOP',
  'Ecuador': 'USD',
  'Egypt': 'EGP',
  'El Salvador': 'USD',
  'Equatorial Guinea': 'XAF',
  'Eritrea': 'ERN',
  'Estonia': 'EUR',
  'Ethiopia': 'ETB',
  'Falkland Islands': 'FKP',
  'Faroe Islands': 'DKK',
  'Fiji': 'FJD',
  'Finland': 'EUR',
  'France': 'EUR',
  'French Guiana': 'EUR',
  'French Polynesia': 'XPF',
  'French Southern Territories': 'EUR',
  'Gabon': 'XAF',
  'Gambia': 'GMD',
  'Georgia': 'GEL',
  'Germany': 'EUR',
  'Ghana': 'GHS',
  'Gibraltar': 'GIP',
  'Greece': 'EUR',
  'Greenland': 'DKK',
  'Grenada': 'XCD',
  'Guadeloupe': 'EUR',
  'Guam': 'USD',
  'Guatemala': 'GTQ',
  'Guernsey': 'GBP',
  'Guinea': 'GNF',
  'Guinea-Bissau': 'XOF',
  'Guyana': 'GYD',
  'Haiti': 'HTG',
  'Honduras': 'HNL',
  'Hong Kong SAR China': 'HKD',
  'Hungary': 'HUF',
  'Iceland': 'ISK',
  'India': 'INR',
  'Indonesia': 'IDR',
  'Iran': 'IRR',
  'Iraq': 'IQD',
  'Ireland': 'EUR',
  'Isle of Man': 'GBP',
  'Israel': 'ILS',
  'Italy': 'EUR',
  'Jamaica': 'JMD',
  'Japan': 'JPY',
  'Jersey': 'GBP',
  'Jordan': 'JOD',
  'Kazakhstan': 'KZT',
  'Kenya': 'KES',
  'Kiribati': 'AUD',
  'Kuwait': 'KWD',
  'Kyrgyzstan': 'KGS',
  'Laos': 'LAK',
  'Latvia': 'EUR',
  'Lebanon': 'LBP',
  'Lesotho': 'LSL',
  'Liberia': 'LRD',
  'Libya': 'LYD',
  'Liechtenstein': 'CHF',
  'Lithuania': 'EUR',
  'Luxembourg': 'EUR',
  'Macao SAR China': 'MOP',
  'Madagascar': 'MGA',
  'Malawi': 'MWK',
  'Malaysia': 'MYR',
  'Maldives': 'MVR',
  'Mali': 'XOF',
  'Malta': 'EUR',
  'Marshall Islands': 'USD',
  'Martinique': 'EUR',
  'Mauritania': 'MRU',
  'Mauritius': 'MUR',
  'Mayotte': 'EUR',
  'Mexico': 'MXN',
  'Micronesia': 'USD',
  'Moldova': 'MDL',
  'Monaco': 'EUR',
  'Mongolia': 'MNT',
  'Montenegro': 'EUR',
  'Montserrat': 'XCD',
  'Morocco': 'MAD',
  'Mozambique': 'MZN',
  'Myanmar (Burma)': 'MMK',
  'Namibia': 'NAD',
  'Nauru': 'AUD',
  'Nepal': 'NPR',
  'Netherlands': 'EUR',
  'New Caledonia': 'XPF',
  'New Zealand': 'NZD',
  'Nicaragua': 'NIO',
  'Niger': 'XOF',
  'Nigeria': 'NGN',
  'Niue': 'NZD',
  'Norfolk Island': 'AUD',
  'North Korea': 'KPW',
  'North Macedonia': 'MKD',
  'Northern Mariana Islands': 'USD',
  'Norway': 'NOK',
  'Oman': 'OMR',
  'Pakistan': 'PKR',
  'Palau': 'USD',
  'Palestinian Territories': 'ILS',
  'Panama': 'PAB',
  'Papua New Guinea': 'PGK',
  'Paraguay': 'PYG',
  'Peru': 'PEN',
  'Philippines': 'PHP',
  'Pitcairn Islands': 'NZD',
  'Poland': 'PLN',
  'Portugal': 'EUR',
  'Puerto Rico': 'USD',
  'Qatar': 'QAR',
  'Romania': 'RON',
  'Russia': 'RUB',
  'Rwanda': 'RWF',
  'Réunion': 'EUR',
  'Samoa': 'WST',
  'San Marino': 'EUR',
  'Saudi Arabia': 'SAR',
  'Senegal': 'XOF',
  'Serbia': 'RSD',
  'Seychelles': 'SCR',
  'Sierra Leone': 'SLL',
  'Singapore': 'SGD',
  'Sint Maarten': 'ANG',
  'Slovakia': 'EUR',
  'Slovenia': 'EUR',
  'Solomon Islands': 'SBD',
  'Somalia': 'SOS',
  'South Africa': 'ZAR',
  'South Korea': 'KRW',
  'South Sudan': 'SSP',
  'Spain': 'EUR',
  'Sri Lanka': 'LKR',
  'St. Barthélemy': 'EUR',
  'St. Helena': 'SHP',
  'St. Kitts & Nevis': 'XCD',
  'St. Lucia': 'XCD',
  'St. Martin': 'EUR',
  'St. Pierre & Miquelon': 'EUR',
  'St. Vincent & Grenadines': 'XCD',
  'Sudan': 'SDG',
  'Suriname': 'SRD',
  'Svalbard & Jan Mayen': 'NOK',
  'Swaziland': 'SZL',
  'Sweden': 'SEK',
  'Switzerland': 'CHF',
  'Syria': 'SYP',
  'Taiwan': 'TWD',
  'Tajikistan': 'TJS',
  'Tanzania': 'TZS',
  'Thailand': 'THB',
  'Timor-Leste': 'USD',
  'Togo': 'XOF',
  'Tokelau': 'NZD',
  'Tonga': 'TOP',
  'Trinidad & Tobago': 'TTD',
  'Tunisia': 'TND',
  'Turkey': 'TRY',
  'Turkmenistan': 'TMT',
  'Turks & Caicos Islands': 'USD',
  'Tuvalu': 'AUD',
  'Uganda': 'UGX',
  'Ukraine': 'UAH',
  'United Arab Emirates': 'AED',
  'United Kingdom': 'GBP',
  'United States': 'USD',
  'U.S. Virgin Islands': 'USD',
  'Uruguay': 'UYU',
  'Uzbekistan': 'UZS',
  'Vanuatu': 'VUV',
  'Vatican City': 'EUR',
  'Venezuela': 'VES',
  'Vietnam': 'VND',
  'Wallis & Futuna': 'XPF',
  'Western Sahara': 'MAD',
  'Yemen': 'YER',
  'Zambia': 'ZMW',
  'Zimbabwe': 'ZWL',
}


